version: 1
formatters:
  main_formatter:
    format: "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
handlers:
  main_handler:
    class: logging.StreamHandler
    formatter: main_formatter
root:
  handlers:
    - main_handler
  level: DEBUG
