from typing import Any

def figure() -> Figure:
    ...

def close(fig: Figure) -> None:
    ...

class Figure:
    def gca(self, ) -> Axes:
        ...
    def savefig(self, *args: Any, **kwargs: Any) -> None:
        ...

# TODO: be more specific
class Axes:
    def plot(self, *args: Any, **kwargs: Any) -> None:
        ...
    def set_xlabel(self, *args: Any, **kwargs: Any) -> None:
        ...
    def set_ylabel(self, *args: Any, **kwargs: Any) -> None:
        ...
